language: php
services:
- mysql
php:
- 7.1
dist: trusty
sudo: true
before_install:
- sudo service mysql stop || echo "mysql not stopped"
- sudo stop mysql-5.6 || echo "mysql-5.6 not stopped"
- echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
- wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
- sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
- sudo apt-get update -q
- sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
- sudo mysql_upgrade
- mysql -e 'CREATE DATABASE IF NOT EXISTS strong;'
- composer self-update
- composer validate --no-check-all --ansi
- composer install -n
- cp .env.example .env
- php artisan migrate
- php artisan db:seed
- vendor/bin/phpunit --coverage-clover=coverage.xml
- rm .env
after_success:
- bash <(curl -s https://codecov.io/bash)
- echo "Unicorn Time"
deploy:
  - provider: script
    script: ./scripts/travis.sh
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: ./scripts/travis.sh
    skip_cleanup: false
    on:
      branch: master
